# Generated by Django 4.2.10 on 2024-02-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['-created_on']},
        ),
    ]
