# Generated by Django 4.2.10 on 2024-03-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_art_artist_alter_like_user_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='year',
        ),
    ]
