# Generated by Django 4.2.10 on 2024-03-12 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_remove_art_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
