# Generated by Django 4.2.10 on 2024-02-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artistprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
