# Generated by Django 4.2.10 on 2024-03-07 17:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artistprofile_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RU', 'Regular User'), ('AR', 'Artist'), ('AD', 'Admin')], default='RU', max_length=2)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('location', models.TextField()),
                ('profile_image', cloudinary.models.CloudinaryField(default='profile_placeholder', max_length=255, verbose_name='profile_image')),
                ('about', models.TextField()),
            ],
        ),
    ]
