# Generated by Django 4.2.10 on 2024-03-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_art_artist_alter_like_user_alter_review_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
